server:
  port: 8080
  contextPath: /CarSharingAndria
---
spring:
  profiles: local,default
datasource:
  csa:
    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net
    username: befbca17442f08
    password: b93c653d
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: heroku_dde502835bb2f29
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod
datasource:
  csa:
    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net
    username: befbca17442f08
    password: b93c653d
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: heroku_dde502835bb2f29
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect